
       DROP TABLE IF EXISTS hana_customer;

       CREATE TABLE IF NOT EXISTS hana_customer (
       personmobilephone    string,
personbirthdate      string ,
      last_update_date__pc string ,
      corporate_client__c  boolean ,      
      personemail   string ,
      pa_name__c    string ,
      create_source__pc    string ,
      account_isactive     boolean    ,   
      language__pc  string ,
      phone  string ,
     latest_retail_date__pc      string ,
     persontitle   string ,
     personotherphone     string ,
     lastmodifieddate     string ,
     data_compliance__pc  string ,
     personhasoptedoutofemail    boolean ,      
     email_opt_in_date__pc       string ,
     membership__pc       string ,
     email_opt_in_flag__pc       string ,
     phone_opt_in_flag__pc       string ,
     last_modify_source__c       string ,
     employee_number__c   string ,
     secondary_email__c   string ,
     primary_customer_address__c string ,
     ispersonaccount      boolean    ,   
     isdeleted     boolean       ,
     primary_customer__c  string ,
     customer_number__c   bigint ,
     anniversary_date__pc string ,
     iswebacc__c   boolean       ,
     latest_retail_store__pc     string ,
     lastmodifiedbyid     string ,
     company__pc   string ,
     age_range__c  string ,
     lastname      string ,
     create_date__pc      string ,
     gender_code_display__pc     string ,
     email_opt_in_date_updated__pc      string ,
     firstname     string ,
     segmentation_flag_e__c      boolean       ,
     referred_by__c       string ,
     phone_opt_in_date__pc       string ,
     salutation    string ,
     membership_date__pc  string ,
     persondonotcall      boolean    ,   
     pa_phone__pc  string ,
     sap_sales_associate__pc     string ,
     member_of_concierge_company__c     boolean      , 
     pa_mobile__pc string ,
     mail_opt_in_flag__pc string ,
     store__pc     string ,
     occupation__pc       string ,
     data_quality_score__pc      int    ,
     mail_opt_in_date__pc string ,
     createdbyid   string ,
     createddate   string ,
     diplomatic_status__c string ,
     pa_email_address__pc string ,
     email_indicator__pc  string ,
     assigned_associate_name     string ,
     pr_address_line_1__c string ,
     pr_city__c    string ,
     pr_country__c string ,
     registered_store     string ,
     ownerid       string ,
     cust_sales_associate_num    string ,
     imp_parent_cust_vc   string ,
     pr_postcode__c       string ,
     pr_address_line_2__c string ,
     pr_address_line_3__c string ,
     pr_province_state__c string ,
     pr_country_name      string ,
     address_last_updated__pc    string ,
     address_modified_date__pc   string ,
     address_type__pc     string ,
     customer_ref_no__c   string ,
     data_policy__pc      boolean   ,    
     e_relationship_created_by__c       string ,
     id_1   string ,
     alias  string ,
     explicit_parent_id__c       string ,
     explicit_parent_id_hana     string ,
     explicit_parent_modified_date__c   string ,
     first_any_store__pc  string ,
     first_retail_store__pc      string ,
     gender__pc      string,
     createdbyid_1 string ,
     createddate_1 string ,
     department    string ,
     division      string ,
     i_relationship_created_id__c       string ,
     implicit_parent_customer__c string ,
     implicit_parent_modified_date__c   string ,
     lastactivitydate     string ,
     sap_employee_number__c      string ,
     sap_employee_type__c string ,
     systemmodstamp       string ,
     marketing_inactive__pc      boolean       ,
     match_group__pc      string ,
     personcontactid      string ,
    personleadsource     string ,
    personmailingcity    string ,
    personmailingcountry string ,
    personmailingpostalcode     string ,
    personmailingstate   string ,
    personmailingstreet  string ,
    segment_flag_e__pc   boolean       ,
    sf4twitter__fcbk_user_id__pc       string ,
    sf4twitter__twitter_user_id__pc    string ,
    sf4twitter__twitter_username__pc   string ,
    site   string ,
    type   string ,
    email_opt_in  boolean     ,  
    phone_opt_in  boolean    ,   
    mail_opt_in   string ,
    id     string 
)
  ROW FORMAT DELIMITED FIELDS TERMINATED BY ','
  STORED AS TEXTFILE
  LOCATION '${hiveconf:MY.HDFS.DIR}/hana_customer/';

DROP TABLE IF EXISTS cust;

CREATE TABLE IF NOT EXISTS cust (
       parent_id string, 
       customer_number bigint,
       lead_id string,
       lead_number bigint,
       type string,
       bronze boolean,
       create_date date,
       source string,
       first_name string,
       last_name string,
       alias string,
       salutation string,
       gender string,
       language string,
       occupation string,
       contactable boolean,
       phone string,
       secondary_phone string,
       phone_opt_in_flag boolean,
       email string,
       secondary_email string,
       email_opt_in_flag boolean,
       postcode string,
       street string,
       city string,
       state string,
       country_code string,
       country_description string,
       mail_opt_in_flag boolean,
       date_of_birth date,
       company string,
       membership string,
       account_isactive boolean,
       address_modified_date date,
       address_type string,
       age_range string,
       data_compliance string,
       data_quality_score int,
       department string,
       diplomatic_status string,
       division string,
       e_relationship_created_by string,
       email_indicator string,
       marketing_inactive boolean,
       annual_revenue string,
       convertedrccountid string,
       convertedcontactid string,
       converteddate date,
       isconverted boolean,
       facebook_id string,
       lead_prize string,
       lead_status string,
       x3rd_party_data string,
       data_policy boolean,
       createdbyid string,
       createddate date,
       lastmodifiedbyid string
       ) 
ROW FORMAT DELIMITED FIELDS TERMINATED BY ','
  STORED AS TEXTFILE
  LOCATION '${hiveconf:MY.HDFS.DIR}/cust/';

DROP TABLE IF EXISTS hana_user;

CREATE TABLE IF NOT EXISTS hana_user (
      systemmodstamp       string ,
      companyname   string ,
     sap_employee_number__c      string ,
      alias  string ,
      sales_associate_number__c   string ,
      firstname     string ,
      createddate   string ,
      timezonesidkey       string ,
      division      string ,
      email_type__c string ,
     createdbyid   string ,
     department    string ,
     localesidkey  string ,
     email  string ,
     phone  string ,
     username      string ,
     title  string ,
     name   string ,
     sap_employee_type__c string ,
     lastname      string ,
     mobilephone   string ,
     sap_employee_group__c       string ,
     communitynickname    string ,
     employeenumber       string ,
     lastmodifiedbyid     string ,
     lastmodifieddate     string ,
     isactive      string, 
     id     string 
 ) 
ROW FORMAT DELIMITED FIELDS TERMINATED BY ','
  STORED AS TEXTFILE
  LOCATION '${hiveconf:MY.HDFS.DIR}/hana_user/';