SELECT NULL,
       NULL,
       hl.id,
       hl.record_number__c,
       CASE lower(isconverted)
           WHEN 'true' THEN 'CUST'
           ELSE 'LEAD'
       END AS TYPE,
       NULL,
       NULL,
       hl.leadsource,
       hl.firstname,
       hl.lastname,
       NULL,
       hl.salutation,
       hl.gender__c,
       NULL,
       NULL,
       CAST((CASE WHEN lower(hl.hasoptedoutofemail) = 'true' THEN TRUE ELSE FALSE END) AS BOOLEAN),
       hl.phone,
       NULL,
       NULL,
       hl.email,
       NULL,
       NULL,
       hl.postalcode,
       hl.street,
       hl.city,
       hl.STATE,
       hl.country,
       hl.country_description__c,
       NULL,
       TO_DATE(FROM_UNIXTIME(UNIX_TIMESTAMP(hl.date_of_birth__c, 'yyyy.MM.dd'), 'yyyy-MM-dd')),
       hl.company,
       NULL,
       NULL,
       NULL,
       NULL,
       NULL,
       NULL,
       NULL,
       NULL,
       NULL,
       NULL,
       NULL,
       NULL,
       NULL,
       hl.annualrevenue,
       hl.convertedaccountid,
       hl.convertedcontactid,
       TO_DATE(FROM_UNIXTIME(UNIX_TIMESTAMP(hl.converteddate, 'yyyy.MM.dd'), 'yyyy-MM-dd')),
       CAST((CASE WHEN lower(hl.isconverted) = 'true' THEN TRUE ELSE FALSE END) AS BOOLEAN),
       hl.facebook_id__c,
       hl.prize__c,
       hl.status,
       hl.x3rd_party_data__c,
       CAST((CASE WHEN lower(hl.data_policy__c) = 'true' THEN TRUE ELSE FALSE END) AS BOOLEAN),
       hu.name,
       TO_DATE(FROM_UNIXTIME(UNIX_TIMESTAMP(hl.createddate, 'yyyy.MM.dd'), 'yyyy-MM-dd')),
       hu1.name
FROM hana_lead hl
LEFT OUTER JOIN hana_user hu ON (hl.createdbyid = hu.id)
LEFT OUTER JOIN hana_user hu1 ON (hl.lastmodifiedbyid = hu1.id) LIMIT 5