SELECT hc.imp_parent_cust_vc,
       hc.customer_number__c,
       NULL,
       NULL,
       'CUST',
       NULL,
       TO_DATE(FROM_UNIXTIME(UNIX_TIMESTAMP(hc.create_date__pc, 'yyyy.MM.dd'), 'yyyy-MM-dd')),
       hc.create_source__pc,
       hc.firstname,
       hc.lastname,
       hc.alias,
       hc.salutation,
       hc.gender__pc,
       hc.language__pc,
       hc.occupation__pc,
       CAST((CASE WHEN lower(hc.personhasoptedoutofemail) = 'true' THEN TRUE ELSE FALSE END) AS BOOLEAN),
       hc.phone,
       hc.personotherphone,
       CAST((CASE WHEN lower(hc.email_opt_in_flag__pc) = 'true' THEN TRUE ELSE FALSE END) AS BOOLEAN),
       hc.personemail,
       hc.secondary_email__c,
       CAST((CASE WHEN lower(hc.email_opt_in_flag__pc) = 'true' THEN TRUE ELSE FALSE END) AS BOOLEAN),
       hc.personmailingpostalcode,
       hc.pr_address_line_1__c,
       hc.pr_city__c,
       hc.personmailingstate,
       hc.pr_country__c,
       hc.pr_country_name,
       CAST((CASE WHEN lower(hc.mail_opt_in_flag__pc) = 'true' THEN TRUE ELSE FALSE END) AS BOOLEAN),
       TO_DATE(FROM_UNIXTIME(UNIX_TIMESTAMP(hc.anniversary_date__pc, 'yyyy.MM.dd'), 'yyyy-MM-dd')),
       hc.company__pc,
       hc.membership__pc,
       CAST((CASE WHEN lower(hc.account_isactive) = 'true' THEN TRUE ELSE FALSE END) AS BOOLEAN),
       TO_DATE(FROM_UNIXTIME(UNIX_TIMESTAMP(hc.address_modified_date__pc, 'yyyy.MM.dd'), 'yyyy-MM-dd')),
       hc.address_type__pc,
       hc.age_range__c,
       hc.data_compliance__pc,
       hc.data_quality_score__pc,
       hc.department,
       hc.diplomatic_status__c,
       hc.division,
       hc.e_relationship_created_by__c,
       hc.email_indicator__pc,
       CAST((CASE WHEN lower(hc.marketing_inactive__pc) = 'true' THEN TRUE ELSE FALSE END) AS BOOLEAN),
       NULL,
       NULL,
       NULL,
       NULL,
       NULL,
       NULL,
       NULL,
       NULL,
       NULL,
       CAST((CASE WHEN lower(hc.data_policy__pc) = 'true' THEN TRUE ELSE FALSE END) AS BOOLEAN),
       hu.name,
       TO_DATE(FROM_UNIXTIME(UNIX_TIMESTAMP(hc.createddate, 'yyyy.MM.dd'), 'yyyy-MM-dd')),
       hu1.name
FROM hana_customer hc
JOIN hana_customer hc1 ON (hc.id = hc1.imp_parent_cust_vc)
JOIN bronze b ON ( b.parent_sf_id=hc1.imp_parent_cust_vc)
LEFT OUTER JOIN hana_user hu ON (hc.createdbyid = hu.id)
LEFT OUTER JOIN hana_user hu1 ON (hc.lastmodifiedbyid = hu1.id) LIMIT 5